# SPDX-License-Identifier: MPL-2.0

[package]
name = "noctane-gpu"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
bitfield = "0.13"
noctane-util = { path = "../util" }
tracing = "0.1"
