# SPDX-License-Identifier: MPL-2.0

[package]
name = "noctane-gpu"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
bitfield = "0.13"
bytemuck = "1.9"
minifb = "0.23"
noctane-util = { path = "../util" }
ringbuffer = "0.8"
tracing = "0.1"
wgpu = "0.12"
