# SPDX-License-Identifier: MPL-2.0

array_width = 50
chain_width = 50
combine_control_expr = false
comment_width = 100
condense_wildcard_suffixes = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
license_template_path = "rustfmt.license-template"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
required_version = "1.4.38"
unstable_features = true
use_field_init_shorthand = true
version = "Two"
wrap_comments = true
