# SPDX-License-Identifier: MPL-2.0

[package]
name = "noctane"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[[bench]]
name = "cpu"
harness = false

[dependencies]
noctane-cpu = { path = "../cpu" }
noctane-gpu = { path = "../gpu" }
noctane-util = { path = "../util" }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
criterion = "0.3"
pollster = "0.2"
wgpu-types = "0.12"
winit = "0.26"
