# SPDX-License-Identifier: MPL-2.0

[package]
name = "noctane-util"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = "1.0"
futures = "0.3"
minifb = "0.23"
wgpu = "0.12"
